# This workflow handles contact form submissions via GitHub Issues
name: Handle Contact Form

on:
  issues:
    types: [opened]

jobs:
  send-to-telegram:
    if: contains(github.event.issue.title, '[CONTACT FORM]')
    runs-on: ubuntu-latest
    steps:
      - name: Send to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="${{ github.event.issue.body }}"
          TELEGRAM_MESSAGE="🔔 New Website Contact
          
          📝 Message: ${MESSAGE}
          👤 From: ${{ github.event.issue.user.login }}
          🔗 GitHub Issue: ${{ github.event.issue.html_url }}
          ⏰ Time: $(date)"
          
          curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{
              \"chat_id\": \"${TELEGRAM_CHAT_ID}\",
              \"text\": \"${TELEGRAM_MESSAGE}\"
            }"
            
      - name: Close and label issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed',
              labels: ['contact-form', 'processed']
            });
